### ISSUE TITLE
HKT export issue, possibly connected to admin privileges

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#114]
```py
Traceback (most recent call last):
  File "C:\Users\Alexander\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_8_0\export\seut_ot_export.py", line 50, in execute
    SEUT_OT_ExportHKT.export_HKT(self, context, True)
  File "C:\Users\Alexander\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_8_0\export\seut_ot_exportHKT.py", line 88, in export_HKT
    process_fbximporterhkt_to_final_hkt_for_mwm(self, scene, path, settings, hktfile, hktfile)
  File "C:\Users\Alexander\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_8_0\export\havok\seut_havok_hkt.py", line 32, in process_fbximporterhkt_to_final_hkt_for_mwm
    successfulExitCodes=[0,1])    
  File "C:\Users\Alexander\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_8_0\export\seut_export_utils.py", line 504, in callTool
    out = subprocess.check_output(cmdline, cwd=cwd, stderr=subprocess.STDOUT, shell=True)
  File "S:\SteamLibrary\steamapps\common\Blender\2.81\python\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "S:\SteamLibrary\steamapps\common\Blender\2.81\python\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['S:\\3DProjects\\SEUT\\Tools\\Havok\\HavokContentTools\\hctStandAloneFilterManager.exe', '-t', '-s', 'C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\space_engineers_70l0flcy.hko', '-p', 'S:\\3DProjects\\Export\\Models\\CubeBlocks\\Small\\ECSM_FlareChaffLauncher_Small\\ECSM_FlareChaffLauncher_Small.hkt', 'S:\\3DProjects\\Export\\Models\\CubeBlocks\\Small\\ECSM_FlareChaffLauncher_Small\\ECSM_FlareChaffLauncher_Small.hkt']' returned non-zero exit status 4294967295.

location: <unknown location>:-1
```

```py
Command: S:\3DProjects\SEUT\Tools\Havok\HavokContentTools\hctStandAloneFilterManager.exe -t -s C:\Users\ALEXAN~1\AppData\Local\Temp\space_engineers_6f3sezav.hko -p S:\3DProjects\Export\Models\CubeBlocks\Small\ECSM_FlareChaffLauncher_Small\ECSM_FlareChaffLauncher_Small.hkt S:\3DProjects\Export\Models\CubeBlocks\Small\ECSM_FlareChaffLauncher_Small\ECSM_FlareChaffLauncher_Small.hkt 
Error: Load failed
Could not find hctFilterManager.dll.
```

Error does not appear if Blender is run as admin. DLLs are unprotected so that's not the issue either.

**Comment by enenra** [comment]
According to @cstahlhut this is not an issue with the addon but with user access settings on the user side. Not something we can fix.
