### ISSUE TITLE
Subpart linking issue with edit mode

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#131]
report here: https://discordapp.com/channels/417308639343280131/663131868476211213/678958253799112706

**Comment by enenra** [comment]
Possibly related:
This happened after I ran structure conversion on Wizard's block.blend and tried to turn on mirroring mode:

```py
SEUT: Cannot find mirror axis materials. Re-link 'MatLib_Presets.blend'! (026)
Traceback (most recent call last):
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_ot_mirroring.py", line 52, in execute
    SEUT_OT_Mirroring.mirroringSetup(self, context)
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_ot_mirroring.py", line 206, in mirroringSetup
    linkSubpartScene(self, scene, emptyX, collection)
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_utils.py", line 53, in linkSubpartScene
    bpy.ops.object.duplicate(linked=True)
  File "c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.duplicate.poll() failed, context is incorrect

location: c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py:201

location: c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py:201
Error: Traceback (most recent call last):
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_ot_mirroring.py", line 52, in execute
    SEUT_OT_Mirroring.mirroringSetup(self, context)
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_ot_mirroring.py", line 206, in mirroringSetup
    linkSubpartScene(self, scene, emptyX, collection)
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_utils.py", line 53, in linkSubpartScene
    bpy.ops.object.duplicate(linked=True)
  File "c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.duplicate.poll() failed, context is incorrect

location: c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py:201

Traceback (most recent call last):
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_scene.py", line 25, in update_MirroringToggle
    bpy.ops.scene.mirroring()
  File "c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_ot_mirroring.py", line 52, in execute
    SEUT_OT_Mirroring.mirroringSetup(self, context)
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_ot_mirroring.py", line 206, in mirroringSetup
    linkSubpartScene(self, scene, emptyX, collection)
  File "C:\Users\DESKTOP-LUKAS\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\src\seut_utils.py", line 53, in linkSubpartScene
    bpy.ops.object.duplicate(linked=True)
  File "c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.duplicate.poll() failed, context is incorrect

location: c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py:201
```
