### ISSUE TITLE
Issue on export

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#157]
```py
Traceback (most recent call last):
  File "C:\Users\kylew\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_9_8\export\seut_ot_export.py", line 44, in execute
    result_main = SEUT_OT_ExportMain.export_Main(self, context, True)
  File "C:\Users\kylew\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_9_8\export\seut_ot_exportMain.py", line 92, in export_Main
    export_model_FBX(self, context, collections['main'])
  File "C:\Users\kylew\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_9_8\export\seut_export_utils.py", line 333, in export_model_FBX
    export_to_fbxfile(settings, scene, fbxfile, collection.objects, ishavokfbxfile=False)
  File "C:\Users\kylew\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_9_8\export\seut_export_utils.py", line 673, in export_to_fbxfile
    **kwargs # Stores any number of Keyword Arguments into a dictionary called 'fbxSettings'.
  File "C:\Program Files\blender-2.81-d590db83705b-windows64\2.81\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3092, in save_single
    fbx_objects_elements(root, scene_data)
  File "C:\Program Files\blender-2.81-d590db83705b-windows64\2.81\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2892, in fbx_objects_elements
    fbx_data_mesh_elements(objects, me_obj, scene_data, done_meshes)
  File "C:\Program Files\blender-2.81-d590db83705b-windows64\2.81\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 1163, in fbx_data_mesh_elements
    uvlayer.data.foreach_get("uv", t_luv)
RuntimeError: internal error setting the array

location: <unknown location>:-1
```
discussion: https://discordapp.com/channels/@me/539184784237133833/681306111470731293
report: https://discordapp.com/channels/125011928711036928/161758345856811008/681297333924659322

An instance of the main collection existed under the scene collection. Unlinking it from the scene collection fixed the issue. Need to find out where export failed to result in this so this bug here can't happen again.

**Comment by enenra** [comment]
It looks like this may have been the result of an earlier issue that has since been fixed.
