### ISSUE TITLE
Crash on export

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#165]
```py
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_9_85\export\seut_ot_export.py", line 53, in execute
    SEUT_OT_ExportHKT.export_HKT(self, context, True)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_9_85\export\seut_ot_exportHKT.py", line 90, in export_HKT
    export_to_fbxfile(settings, scene, fbxhktfile, collections['hkt'].objects, ishavokfbxfile=True)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_9_85\export\seut_export_utils.py", line 664, in export_to_fbxfile
    **kwargs # Stores any number of Keyword Arguments into a dictionary called 'fbxSettings'.    
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3079, in save_single
    scene_data = fbx_data_from_scene(scene, depsgraph, settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 2302, in fbx_data_from_scene
    ob_to_convert = ob.evaluated_get(depsgraph) if settings.use_mesh_modifiers else ob
TypeError: Object.evaluated_get(): error with argument 1, "depsgraph" -  Function.depsgraph does not support a 'None' assignment Depsgraph type

location: <unknown location>:-1
```
BLEND file: https://discordapp.com/channels/125011928711036928/161758345856811008/682683341727727682

**Comment by enenra** [comment]
Might be related to using wrong MWMB

**Comment by enenra** [comment]
https://discordapp.com/channels/125011928711036928/161758345856811008/682700266507862097 Looks like complexity of collision mesh was the issue.
