### ISSUE TITLE
Error on export when in pose-mode

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#167]
```py
Error: Traceback (most recent call last):
  File "C:\Users\Cheyne\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\src\export\seut_ot_export.py", line 64, in execute
    bpy.ops.object.mode_set(mode=currentMode)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  enum "POSE" not found in ('OBJECT')

location: <unknown location>:-1
```

**Comment by enenra** [comment]
this is probably fine I literally only added a try/except
