### ISSUE TITLE
MWMB crash because of missing UVMs

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#175]
Object does have UVMs, but not on every face. Not sure I can effectively catch that on Blender side.

```py
 System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
       at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
       at System.Collections.Generic.List`1.get_Item(Int32 index)
       at MwmBuilder.MyModelProcessor.TransformScene(Node node, Matrix4x4 transform, Scene input) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\MyModelProcessor.cs:line 770
       at MwmBuilder.MyModelProcessor.FlattenAllTransforms(Node node, Scene input) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\MyModelProcessor.cs:line 742
       at MwmBuilder.MyModelProcessor.FlattenTransforms(Node node, Bone skeleton, Scene input) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\MyModelProcessor.cs:line 733
       at MwmBuilder.MyModelProcessor.ProcessSkeleton(Scene input) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\MyModelProcessor.cs:line 677
       at MwmBuilder.MyModelProcessor.Process(Scene input, String filename, String outputDir, Boolean checkOpenBoundaries, IMyBuildLogger logger) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\MyModelProcessor.cs:line 203
       at MwmBuilder.MyModelBuilder.Build(String filename, String intermediateDir, String outputDir, MyModelConfiguration configuration, Byte[] havokCollisionShapes, Boolean checkOpenBoundaries, Single[] lodDistances, Boolean overrideLods, Func`2 getMaterialByRef, IMyBuildLogger logger) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\MyModelBuilder.cs:line 179
       at MwmBuilder.ProgramContext.ProcessItem(ItemInfo item, String outputDir, Byte[] havokCollisionShapes, Boolean checkOpenBoundaries, Single[] lodDistances, Boolean overrideLods) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\ProgramContext.cs:line 416
       at MwmBuilder.ProgramContext.ProcessFile(String file, String outputDir, Dictionary`2 defaultVars, Boolean exportXml, Boolean forceBuild, Boolean checkOpenBoundaries, String lodDistances, Boolean overrideLods) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\ProgramContext.cs:line 366
       at MwmBuilder.ProgramContext.ProcessFileSafe(String file) in C:\3D_Projects\MWMBSourceEQ\MWMBSourceEQ\ProgramContext.cs:line 158
```
report: https://discordapp.com/channels/417308639343280131/663131868476211213/685111322618495025

**Comment by cstahlhut** [comment]
Run two counts, a count of meshes and a count of UV's by iterating said meshes, if one doesnt match the other when they click that export button throw an error.

**Comment by enenra** [comment]
I can't figure out a way to find whether a specific face has an uv map associated with it unfortunately so this will have to be fixed / caught in the MWMB code.
