### ISSUE TITLE
log spams "SEUT Error: Cannot set SubtypeId to a SubtypeId that already exists in the file for another scene. (018)" 1000+ times

### ISSUE THREAD

**Issue by lAimBotl** [enenra/space-engineers-utilities#189]
this is what I got before it spammed me with that lol.

"Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\space_engineers_utilities_0_9_88\seut_scene.py", line 97, in update_subtypeId
    if scn is not scene and scn.seut.subtypeId == scene.seut.subtypeId:
RecursionError: maximum recursion depth exceeded in comparison
File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\space_engineers_utilities_0_9_88\seut_scene.py", line 92, in update_subtypeId

**Comment by enenra** [comment]
Can you expand on what you were doing at the time? Which functionality you were using etc.

**Comment by lAimBotl** [comment]
I found out how to reproduce it, make a scene, click the box under "file name" but don't type anything, then click "anywhere" else.
