### ISSUE TITLE
Error on adding MountPoint after resize

### ISSUE THREAD

**Issue by mtwombley** [enenra/space-engineers-utilities#196]
```
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\diaga\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\space_engineers_utilities_0_9_89\seut_ot_addMountpointArea.py", line 60, in execute
    area = SEUT_OT_Mountpoints.createArea(context, 'Mountpoint Area ' + side.capitalize(), 1, scale, scale, None, None, collection, bpy.data.objects['Mountpoints ' + side.capitalize()])
  File "C:\Users\diaga\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\space_engineers_utilities_0_9_89\seut_ot_mountpoints.py", line 218, in createArea
    collection.objects.link(area)
RuntimeError: Error: Object 'Mountpoint Area Top' already in collection 'Mountpoints (ConveyorTunnelSloped)'
```

Steps to Repeat:
Resize the face of the MountPoint you want to add to and like a dummy forget to leave edit mode. Press the 'Add Area' button and you get the following error. The problem is it messes up the existing mount point and the error means nothing. If you can detect it, maybe do nothing and give a message that the user is in edit mode.

If you are not in edit mode it works as expected.

**Comment by enenra** [comment]
Thank you, I'll investigate. It sounds like I need to add a mode switch for safety.

**Comment by enenra** [comment]
This looks to be fixed.
