### ISSUE TITLE
Bug when using Copy Settings for new scene

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#238]
```py
Python: Traceback (most recent call last):
  File "C:\Users\enenra\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\src\seut_ot_simple_navigation.py", line 47, in modal
    collections = get_collections(scene)
  File "C:\Users\enenra\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\src\seut_collections.py", line 69, in get_collections
    children = scene.view_layers['SEUT'].layer_collection.children
KeyError: 'bpy_prop_collection[key]: key "SEUT" not found'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\enenra\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\src\seut_ot_simple_navigation.py", line 47, in modal
    collections = get_collections(scene)
  File "C:\Users\enenra\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\src\seut_collections.py", line 69, in get_collections
    children = scene.view_layers['SEUT'].layer_collection.children
KeyError: 'bpy_prop_collection[key]: key "SEUT" not found'

location: <unknown location>:-1
```

**Comment by enenra** [comment]
Fixed in latest commit.
