### ISSUE TITLE
Add error handling for missing Assimp32.dll

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#248]
```cs
: ERROR: 
    C:\Users\Shark\AppData\Roaming\SpaceEngineers\Mods\Naval Engineers\Models\Propeller 5 blade 3x1.fbx:
    Assimp.AssimpException: Error loading unmanaged library from path: Assimp32.dll, see inner exception for details.
The specified module could not be found. (Exception from HRESULT: 0x8007007E) ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
       --- End of inner exception stack trace ---
       at Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path)
       at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
       at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
       at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded()
       at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
       at Assimp.AssimpContext.CreateConfigs()
       at Assimp.AssimpContext.PrepareImport()
       at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
       at MwmBuilder.MyModelBuilder.Build(String filename, String intermediateDir, String outputDir, MyModelConfiguration configuration, Byte[] havokCollisionShapes, Boolean checkOpenBoundaries, Single[] lodDistances, Boolean overrideLods, Func`2 getMaterialByRef, IMyBuildLogger logger) in C:\3D_Projects\MWMBSourceStollie\MyModelBuilder.cs:line 87
       at MwmBuilder.ProgramContext.ProcessItem(ItemInfo item, String outputDir, Byte[] havokCollisionShapes, Boolean checkOpenBoundaries, Single[] lodDistances, Boolean overrideLods) in C:\3D_Projects\MWMBSourceStollie\ProgramContext.cs:line 416
       at MwmBuilder.ProgramContext.ProcessFile(String file, String outputDir, Dictionary`2 defaultVars, Boolean exportXml, Boolean forceBuild, Boolean checkOpenBoundaries, String lodDistances, Boolean overrideLods) in C:\3D_Projects\MWMBSourceStollie\ProgramContext.cs:line 366
       at MwmBuilder.ProgramContext.ProcessFileSafe(String file) in C:\3D_Projects\MWMBSourceStollie\ProgramContext.cs:line 156
```
This happens when a NET framework or other library is missing and MWMB fails.

I can adjust this code in `seut_export_utils.py`
```py
        except subprocess.CalledProcessError as e:
            if self.isLogToolOutput and logfile:
                write_to_log(logfile, e.output, cmdline=cmdline, cwd=cwd, loglines=loglines)
            if e.returncode not in successfulExitCodes:
                if e.returncode == 4294967295:
                    seut_report(self, context, 'ERROR', False, 'E037')
                else:
                    seut_report(self, context, 'ERROR', False, 'E035', str(tooltype))
                raise

            return False
```
`e.output` should contain the error - search that string for the right combination of words to determine the error. Potentially also do this for other errors in MWMB and / or Havok.

Discussion: https://discord.com/channels/125011928711036928/279557714965954561/808241625880854538

**Comment by enenra** [comment]
This implementation is still untested, will close the issue when it's been tested successfully.

**Comment by enenra** [comment]
Also, add SEMREF entry.
