### ISSUE TITLE
Issue with parsing export (output?)

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#273]
https://discord.com/channels/657941006397734912/670912695788371979/836662548048379964
```py
bpy.ops.scene.export()
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\space-engineers-utilities\export\seut_ot_export.py", line 38, in execute
    result = export(self, context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\space-engineers-utilities\export\seut_ot_export.py", line 101, in export
    export_all(self, context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\space-engineers-utilities\export\seut_ot_export.py", line 149, in export_all
    export_mwm(self, context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\space-engineers-utilities\export\seut_ot_export.py", line 385, in export_mwm
    mwmbuilder(self, context, path, path, settings, mwmfile, materials_path)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\space-engineers-utilities\export\seut_mwmbuilder.py", line 22, in mwmbuilder
    logfile=path + scene.seut.subtypeId + '.mwm.log'            
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\space-engineers-utilities\export\seut_export_utils.py", line 611, in callTool
    out_str = out.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 839: invalid start byte

location: <unknown location>:-1
```

**Comment by enenra** [comment]
Could not be reproduced and setting it up in a new file fixed it for the user.
