### ISSUE TITLE
When 1 button exporting and Collision collection is not selected to show, error produced.

### ISSUE THREAD

**Issue by cstahlhut** [enenra/space-engineers-utilities#29]
```
pyTraceback (most recent call last):
  File "C:\Users\Cheyne\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space-engineers-utilities\seut_ot_export.py", line 146, in execute
    bpy.ops.object.export_hkt()
  File "c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Cheyne\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space-engineers-utilities\seut_ot_exportHKT.py", line 58, in execute
    bpy.ops.rigidbody.object_add(type='ACTIVE')
  File "c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.rigidbody.object_add.poll() failed, context is incorrect

location: c:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py:201
```

**Comment by cstahlhut** [comment]
You're more across collections and the error system so I'll leave this with you :D

**Comment by enenra** [comment]
this is checkbox, not eye unchecking, so *excluding from view layer*, according to the popup. Need to investigate what the difference is to determine what to do. I'd say when it's just hidden via eye it should probably be exported anyway (test whether this is possible). But it still needs to throw an error if the collection is unticked in the checkbox.

**Comment by enenra** [comment]
I hate this.
```py
        mainLayerCol = context.view_layer.layer_collection.children['SEUT'].children[collections['main'].name]
        if mainLayerCol.exclude == True:
            self.report({'ERROR'}, "SEUT: Collection 'Main' excluded from view. Export not possible. (017)")
            return {'CANCELLED'}
```
This will catch the issue for main export but if the user moves main to anywhere else it's fucked.

**Comment by enenra** [comment]
I need to recursively search through all view_layer collections for the relevant one and then check whether it's excluded or not.

**Comment by enenra** [comment]
This needs to be added to the other export operators aside from main still
