### ISSUE TITLE
Game Directory in preferences should check for exe

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#320]
```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\space-engineers-utilities\materials\seut_ot_texture_conversion.py", line 137, in execute
    result = mass_convert_textures(self, context, dirs_to_convert, target_dir, 'tif', skip_list=skip_list, log_to_file=True, can_report=True)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\space-engineers-utilities\materials\seut_ot_texture_conversion.py", line 153, in mass_convert_textures
    for file in os.listdir(tex_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Owner\\AppData\\Roaming\\SpaceEngineers\\Content\\Textures\\Models\\Cubes'

location: <unknown location>:-1
```
Game Directory also is valid when you select the appdata folder. It should check for the textures folder existing within it in the validity check when setting it.

**Comment by enenra** [comment]
Works.
