### ISSUE TITLE
EO44 won't export my model

### ISSUE THREAD

**Issue by TiaanSWU** [enenra/space-engineers-utilities#346]
**Describe the bug**
This is from error EO44 I am trying to make a Christmas tree, but it refuses to export the model

**To Reproduce**
1. Click on export 

**Expected behavior**
It to export the Christmas tree for use in game

**Screenshots**

**BLEND file**
Don't share the file It for a server I work and supposed to be unique 

[Christmas_Tree_Space Engineers_Bug.zip](https://github.com/enenra/space-engineers-utilities/files/9946957/Christmas_Tree_Space.Engineers_Bug.zip)

**Versions (please complete the following information):**
 - SEUT version 0.9.96
 - Blender version: 3.3.1

**Additional context**
I think it may be because of the number of leaves and details but I truly don't know tried everything, but it finally told me to submit a bug report so here I am.

**Comment by enenra** [comment]
Hi, could you please send me the log file as described in the error message / in the troubleshooting page on SEMREF?
```
SEUT: An error ocurred during MWM conversion. See *.mwm.log file (generated if 'Delete Temp Files' is toggled off) for details.
```

**Comment by TiaanSWU** [comment]
[Christmas_Tree.mwm.log](https://github.com/enenra/space-engineers-utilities/files/9957069/Christmas_Tree.mwm.log)

**Comment by enenra** [comment]
Well, there you go:
```
    System.Exception: Mesh 'tree.001' has no UV map/channel!
       at MwmBuilder.MyModelBuilder.<Build>g__LogUVError|5_0(Mesh mesh, String message) in C:\Users\cheyn\Google Drive\3D_Projects\MWMBSourceStollie\MyModelBuilder.cs:line 120
       at MwmBuilder.MyModelBuilder.Build(String filename, String intermediateDir, String outputDir, MyModelConfiguration configuration, Byte[] havokCollisionShapes, Boolean checkOpenBoundaries, Single[] lodDistances, Boolean overrideLods, Func`2 getMaterialByRef, IMyBuildLogger logger) in C:\Users\cheyn\Google Drive\3D_Projects\MWMBSourceStollie\MyModelBuilder.cs:line 138
       at MwmBuilder.ProgramContext.ProcessItem(ItemInfo item, String outputDir, Byte[] havokCollisionShapes, Boolean checkOpenBoundaries, Single[] lodDistances, Boolean overrideLods) in C:\Users\cheyn\Google Drive\3D_Projects\MWMBSourceStollie\ProgramContext.cs:line 416
       at MwmBuilder.ProgramContext.ProcessFile(String file, String outputDir, Dictionary`2 defaultVars, Boolean exportXml, Boolean forceBuild, Boolean checkOpenBoundaries, String lodDistances, Boolean overrideLods) in C:\Users\cheyn\Google Drive\3D_Projects\MWMBSourceStollie\ProgramContext.cs:line 366
       at MwmBuilder.ProgramContext.ProcessFileSafe(String file) in C:\Users\cheyn\Google Drive\3D_Projects\MWMBSourceStollie\ProgramContext.cs:line 156
```
Once of your objects doesn't have an UV map.

**Comment by enenra** [comment]
I'm assuming this has been resolved. If not, let me know. :-)
