### ISSUE TITLE
Blender 3.5 import error

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#365]
```py
----------------------------------------------------------------
Time:			2023-04-08 17:35:50
Blender:		3.5.0
SEUT:			1.0.0
----------------------------------------------------------------
Game Dir:		C:\Users\SEUT-USER\Desktop\Steam\steamapps\common\SpaceEngineers\
Assets:			1.3.0	 Path: C:\Users\SEUT-USER\Desktop\SE Mods\
MWMB:			0.3.3	 Path: C:\Users\SEUT-USER\Desktop\SE Mods\Tools\MWMBuilder\MwmBuilder.exe
Havok Path:		C:\Users\SEUT-USER\Desktop\SE Modding Shit\HavokContentTools\hctStandAloneFilterManager.exe
----------------------------------------------------------------
BLEND Path:		C:\Users\SEUT-USER\Desktop\Blender\untitled.blend
Icon Path:		/tmp\
Mod Path:		
Export Path:	
----------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\SEUT-USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\space-engineers-utilities\importing\seut_ot_import_complete.py", line 100, in execute
    col = collections['main'][0]
TypeError: 'NoneType' object is not subscriptable
  File "C:\Users\SEUT-USER\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\space-engineers-utilities\importing\seut_ot_import_complete.py", line 100, in execute
    col = collections['main'][0]
SEUT Info: Successfully exported log to 'C:\Users\SEUT-USER\Desktop\Blender\untitled_2023-04-08_17-35-50.log'. (I001)
```

File: https://discord.com/channels/125011928711036928/161758345856811008/1094376560292806666

**Comment by enenra** [comment]
The issue here is that the SEUT collections were missing. But SEUT also does not have proper error handling in its import to account for that.
