### ISSUE TITLE
Error when following instructions youtube (Chipstix213) and Altasian.net

### ISSUE THREAD

**Issue by TagForMe** [enenra/space-engineers-utilities#367]
**Describe the bug**

followed install instructions from Chipstix213 youtube video 

https://www.youtube.com/watch?v=9xq6XrKL6AQ

as well as tutorial on atlassian.net

https://semref.atlassian.net/wiki/spaces/tutorials/pages/131411/SEUT+Installation+Guide

an error occured that causes textures to not load in when loading model when proceeding afterward.

**Error report**

Read prefs: C:\Users\Anonymous\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
Traceback (most recent call last):
  File "C:\Users\Anonymous\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\space-engineers-utilities\seut_collections.py", line 269, in execute
    temp_mat = create_material()
  File "C:\Users\Anonymous\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\space-engineers-utilities\materials\seut_ot_create_material.py", line 69, in create_material
    material.node_tree.links.new(node_group_node.outputs[0], node_output.inputs[0])
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
Error: Python: Traceback (most recent call last):
  File "C:\Users\Anonymous\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\space-engineers-utilities\seut_collections.py", line 269, in execute
    temp_mat = create_material()
  File "C:\Users\Anonymous\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\space-engineers-utilities\materials\seut_ot_create_material.py", line 69, in create_material
    material.node_tree.links.new(node_group_node.outputs[0], node_output.inputs[0])
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Expected behavior**
No error, conform video tutorial.

**Versions**
 - SEUT version 1.0.0
 - Blender version:  3.5.1

**Comment by enenra** [comment]
Same situation as #368 - issue already resolved.
