### ISSUE TITLE
Missing error handling for MWMB issue on export

### ISSUE THREAD

**Issue by enenra** [enenra/space-engineers-utilities#86]
```py
Traceback (most recent call last):
  File "C:\Users\theod\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_7_0\export\seut_ot_export.py", line 55, in execute
    SEUT_OT_ExportMWM.export_MWM(self, context)
  File "C:\Users\theod\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_7_0\export\seut_ot_exportMWM.py", line 64, in export_MWM
    mwmbuilder(self, context, path, mwmpath, settings, mwmfile, materialspath)
  File "C:\Users\theod\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_7_0\export\seut_mwmbuilder.py", line 10, in mwmbuilder
    settings.callTool(cmdline, cwd=path, logfile=path + scene.seut.subtypeId + '.log')
  File "C:\Users\theod\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\space_engineers_utilities_0_7_0\export\seut_export_utils.py", line 500, in callTool
    out = subprocess.check_output(cmdline, cwd=cwd, stderr=subprocess.STDOUT, shell=True)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.81\python\lib\subprocess.py", line 395, in check_output
    *kwargs).stdout
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.81\python\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\Users\theod\Desktop\SEUT(1)\SEUT\Tools\MwmBuilder(4)\MwmBuilder.exe', '/f', '/s:C:\Users\theod\Documents\..\Desktop\PDC Mod\Models\', '/m:TurretElevation_Large.fbx', '/o:C:\Users\theod\Documents\..\Desktop\PDC Mod\Models\', '/x:C:\Users\theod\Documents\..\Desktop\SEUT(1)\SEUT\Materials\']' returned non-zero exit status 1.

location: <unknown location>:-1
```
https://discordapp.com/channels/125011928711036928/161758345856811008/673413617215078440

**Comment by enenra** [comment]
Not enough info to investigate and the user had previously had issues with wrong external tool setup. A lot of those issues are now prevented in the first place by better checks for external tool path validity. User has also now gotten it to work normally.
Going to set this to complete for now.
